services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        volumes:
            - .:/var/www/html:delegated
            - ./php.ini:/usr/local/etc/php/php.ini
        environment:
            - USER_ID=1000
            - GROUP_ID=1000
        networks:
            - network

    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - network

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz2wsx
            MYSQL_DATABASE: db_school_management_system
            MYSQL_PASSWORD: 1qaz2wsx
        volumes:
            - volume:/var/lib/mysql
        networks:
            - network

volumes:
    volume:


networks:
    network:
        driver: bridge
